// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqEiXRSUJi6qJKoxmFMQ7fA8Kx4FAtq8',
    appId: '1:903275424450:web:ca27ab544bfad20857695b',
    messagingSenderId: '903275424450',
    projectId: 'swiftdrop-da64a',
    authDomain: 'swiftdrop-da64a.firebaseapp.com',
    storageBucket: 'swiftdrop-da64a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHiuM1zVQcPa-bq6Eav8HwSe8m8ceVpg',
    appId: '1:903275424450:android:411b65fd3931ee5c57695b',
    messagingSenderId: '903275424450',
    projectId: 'swiftdrop-da64a',
    storageBucket: 'swiftdrop-da64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qV4Xv2pi5-7EFMzCKXBvD83wXhXq_Rw',
    appId: '1:903275424450:ios:66edc99d58a5274757695b',
    messagingSenderId: '903275424450',
    projectId: 'swiftdrop-da64a',
    storageBucket: 'swiftdrop-da64a.firebasestorage.app',
    iosBundleId: 'com.example.swiftdrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3qV4Xv2pi5-7EFMzCKXBvD83wXhXq_Rw',
    appId: '1:903275424450:ios:66edc99d58a5274757695b',
    messagingSenderId: '903275424450',
    projectId: 'swiftdrop-da64a',
    storageBucket: 'swiftdrop-da64a.firebasestorage.app',
    iosBundleId: 'com.example.swiftdrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARqEiXRSUJi6qJKoxmFMQ7fA8Kx4FAtq8',
    appId: '1:903275424450:web:275907399c976c7557695b',
    messagingSenderId: '903275424450',
    projectId: 'swiftdrop-da64a',
    authDomain: 'swiftdrop-da64a.firebaseapp.com',
    storageBucket: 'swiftdrop-da64a.firebasestorage.app',
  );
}
